title: Roman B.
#logo: 1.png
description: Listen. Understand. Implement. Simplify.
show_downloads: false
#theme: jekyll-theme-slate 
theme: jekyll-theme-modernist 
#theme: jekyll-theme-midnight 
plugins:
  - jekyll-seo-tag
email: bondarenko.roman@gmail.com
